CREATE USER urbanfood_user IDENTIFIED BY hello123;

GRANT ALL PRIVILEGES TO urbanfood_user;

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('admin', 'customer', 'supplier')) NOT NULL
);

INSERT INTO users (username, password, role) VALUES ('admin', 'admin', 'admin');

